<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LauncherBridge</RootNamespace>
    <AssemblyName>LauncherBridge</AssemblyName>
    <Version>1.4.0</Version>
    
    <ApplicationIcon>icon.ico</ApplicationIcon>
    
    <!-- Windows target & single file executable properties -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
